develop_-_background_
latusikl/PhotoPlus pull request #27
Opened 2020-04-20 14:16 UTC by syphzur

2020-04-20 14:29 UTC, Suchar230 commented on PhotoPlusFrontend/PhotoPlus/src/styles.scss
> +  background-image: url('https://upload.wikimedia.org/wikipedia/commons/1/1a/Abstract-background-white-12.jpg');
very instructive

2020-04-20 14:29 UTC, Suchar230 commented on PhotoPlusFrontend/PhotoPlus/src/styles.scss
> +  opacity: 0.9;
why opacity???? pls do not opacity

2020-04-20 18:47 UTC, latusikl requested changes
Resolve issues mentioned by Suchar.

2020-04-20 20:26 UTC, dsuchy approved these changes

2020-04-20 20:26 UTC, dsuchy approved these changes

2020-04-20 20:27 UTC, dsuchy approved these changes

2020-04-21 12:51 UTC, margawron approved these changes

2020-04-21 13:24 UTC, merged