Fixed auth URIS.
latusikl/PhotoPlus pull request #37
Opened 2020-04-23 21:32 UTC by margawron

2020-04-24 10:05 UTC, syphzur approved these changes

2020-04-24 10:08 UTC, syphzur requested changes
delete public urls from admin role

2020-04-24 10:08 UTC, syphzur commented on PhotoPlusBackend/photoplus/src/main/resources/roleConfig.xml
> +                <access>/picture/single</access>
/picture/single url is not protected by security

2020-04-24 13:08 UTC, margawron commented on PhotoPlusBackend/photoplus/src/main/resources/roleConfig.xml
> +                <access>/picture/single</access>
Check bf0ba94

2020-04-24 16:48 UTC, latusikl requested changes

2020-04-24 16:48 UTC, latusikl commented on PhotoPlusBackend/photoplus/src/main/resources/roleConfig.xml
> -                <access>category/all</access>
You should add endpoints which have to be accessible to all to role all.

2020-04-25 10:21 UTC, syphzur approved these changes

2020-04-25 10:21 UTC, syphzur approved these changes

2020-04-25 10:32 UTC, latusikl approved these changes

2020-04-25 10:32 UTC, merged