Completed forum
latusikl/PhotoPlus pull request #51
Opened 2020-04-30 18:27 UTC by margawron

Fully functional forum, has really crude css styling.

2020-04-30 19:53 UTC, syphzur requested changes
please delete xml file from pull request

2020-04-30 19:53 UTC, syphzur commented on PhotoPlusBackend/photoplus/.idea/intellij-javadocs-4.0.1.xml
> +<?xml version="1.0" encoding="UTF-8"?>
why

2020-04-30 19:53 UTC, syphzur commented on PhotoPlusBackend/photoplus/.idea/intellij-javadocs-4.0.1.xml
> +<?xml version="1.0" encoding="UTF-8"?>
pls dont to that

2020-04-30 19:54 UTC, dsuchy requested changes

2020-04-30 19:54 UTC, Suchar230 commented on PhotoPlusBackend/photoplus/.idea/intellij-javadocs-4.0.1.xml
> +  <component name="JavaDocConfiguration">
oh no

2020-04-30 19:55 UTC, dsuchy requested changes
W H Y ? ?

W H Y ? ?

2020-04-30 19:56 UTC, margawron commented on PhotoPlusBackend/photoplus/.idea/intellij-javadocs-4.0.1.xml
> +<?xml version="1.0" encoding="UTF-8"?>
guess thats intelij making this ...

2020-04-30 20:02 UTC, margawron commented on PhotoPlusBackend/photoplus/.idea/intellij-javadocs-4.0.1.xml
> +  <component name="JavaDocConfiguration">
Fixed in e07995e

2020-04-30 20:03 UTC, margawron commented on PhotoPlusBackend/photoplus/.idea/intellij-javadocs-4.0.1.xml
> +<?xml version="1.0" encoding="UTF-8"?>
Fixed in e07995e

2020-04-30 20:16 UTC, syphzur commented on PhotoPlusBackend/photoplus/.idea/intellij-javadocs-4.0.1.xml
> +<?xml version="1.0" encoding="UTF-8"?>
thanks

2020-04-30 20:17 UTC, Suchar230 commented on PhotoPlusBackend/photoplus/.idea/intellij-javadocs-4.0.1.xml
> +  <component name="JavaDocConfiguration">
Very nice

2020-04-30 22:33 UTC, syphzur approved these changes

2020-04-30 22:34 UTC, xPapla approved these changes
dobra robota, ale nie kasuj angulara

2020-05-01 19:02 UTC, dsuchy approved these changes

2020-05-01 19:03 UTC, merged