develop_rating
latusikl/PhotoPlus pull request #99
Opened 2020-05-17 22:42 UTC by tomjur2107

2020-05-17 23:21 UTC, dsuchy requested changes

2020-05-17 23:21 UTC, dsuchy commented on PhotoPlusFrontend/PhotoPlus/src/app/components/product/product.component.scss
> +  margin-left: 41.2%;
what are you trying to achieve here?

2020-05-17 23:21 UTC, Suchar230 commented on PhotoPlusFrontend/PhotoPlus/src/app/components/product/product.component.scss
> +}
https://stackoverflow.com/questions/44960998/css-rating-css-system

2020-05-17 23:21 UTC, Suchar230 commented on PhotoPlusFrontend/PhotoPlus/src/app/components/product/product.component.ts
> +      modalRef.componentInstance.message = "You rated product.";
I think modal here is unnecessary

2020-05-17 23:21 UTC, Suchar230 commented on PhotoPlusFrontend/PhotoPlus/src/app/services/rating/rating.service.ts
> +    console.log(params)
remove console logs

2020-05-17 23:21 UTC, Suchar230 commented on PhotoPlusFrontend/PhotoPlus/src/app/components/product/product.component.scss
> +  top:-9999px;
why

2020-05-17 23:26 UTC, dsuchy requested changes

2020-05-17 23:26 UTC, Suchar230 commented on PhotoPlusFrontend/PhotoPlus/src/app/components/product/product.component.scss
> +  left:-9999px;
W H Y

2020-05-17 23:26 UTC, Suchar230 commented on PhotoPlusFrontend/PhotoPlus/src/app/components/product/product.component.ts
> +    this.rating = new Rating;
how

2020-05-17 23:26 UTC, Suchar230 commented on PhotoPlusFrontend/PhotoPlus/src/app/components/product/product.component.ts
> +    this.rating = new Rating;
how

2020-05-17 23:28 UTC, Suchar230 commented on PhotoPlusFrontend/PhotoPlus/src/app/components/product/product.component.ts
> -    this.content = document.getElementById("area")
very nice keep it up

2020-05-18 09:51 UTC, syphzur commented on PhotoPlusFrontend/PhotoPlus/src/app/components/product/product.component.ts
> +      modalRef.componentInstance.message = "You rated product.";
i think it is

2020-05-18 09:51 UTC, syphzur commented on PhotoPlusFrontend/PhotoPlus/src/app/components/product/product.component.ts
> +      modalRef.componentInstance.message = "You rated product.";
just leave it here

2020-05-18 15:47 UTC, Suchar230 commented on PhotoPlusFrontend/PhotoPlus/src/app/components/product/product.component.ts
> +      modalRef.componentInstance.message = "You rated product.";
ok

2020-05-18 15:51 UTC, margawron requested changes
Please merge with develop.

2020-05-18 23:45 UTC, margawron approved these changes

2020-05-18 23:46 UTC, margawron commented
Improved styling, now it looks good.

2020-05-18 23:53 UTC, syphzur approved these changes

2020-05-19 10:13 UTC, dsuchy approved these changes

2020-05-19 10:15 UTC, merged